import type { Metadata } from "next";
import { Geist, Geist_Mono, Mali} from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const mali = Mali({ 
  subsets: ["thai","latin"], 
  weight: ["400", "700"],
  variable: "--font-mali", // 👈 ตั้งชื่อตัวแปรให้ฟอนต์
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} ${mali.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col font-mali">
         {children}
        </body>
    </html>
  );
}
