
// app/layout.tsx

import type { Metadata } from "next";
import { Geist, Geist_Mono, Mali} from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const mali = Mali({ 
  subsets: ["thai","latin"], 
  weight: ["400", "700"],
  variable: "--font-mali", // 👈 ตั้งชื่อตัวแปรให้ฟอนต์
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="th"
      className={`${geistSans.variable} ${geistMono.variable} 
        ${mali.variable} h-full antialiased`}
    >
      <body className="min-h-full font-mali relative overflow-hoidden">

        {/*gif on this will show all page */}
        
        <img
          src="/background.gif"
          alt="Background"
          className="fixed top-0 left-0 w-full h-full object-cover z-0 pointr"
        />

          {/* ต้องมี z-10 เพื่อให้อยู่เหนือ gif /  need z-10 to button or any thing will on gif */}
          <div className="relative z-10 min-h-screen flex flex-col">
            {children}
          </div>

        </body>
    </html>
  );
}
